const slugify = require('slugify');
const md5 = require('md5');
const {DateTime} = require('luxon');

const fragments = [
    'curtis',
    'curt',
    'dan',
    'daniel',
    'danielle',
    'jenn',
    'jon',
    'jennifer',
    'jonnifer',
    'nick',
    'nicholas',
    'nikki',
    'jason',
    'jayson',
    'jesse',
    'jessi',
    'ron',
    'ronald',
    'bronald',
    'ronaldo',
    'graham',
    'grahamina',
    'sean',
    'seanna',
    'neil',
    'gunter',
    'gunther',
    'kyle',
    'kylie',
    'nyx',
    'ash',
    'ashley',
    'slorg',
    'bashley',
    'squiggly',
    'kiro',
    'bryan',
    'nifty',
    'katie',
    'fusl',
    'squid',
    'orels',
    'brian',
    'calle',
    'callie',
    'chris',
    'christopher',
    'hamza',
    'tina',
    'alex',
    'lexi',
    'alexis',
    'pontus',
    'rich',
    'thomas',
    'tomas',
    'isaac',
    'euan',
    'herman',
    'craig',
    'sassy',
    'dave',
    'david',
    'todd',
    'tod',
    'ars',
    'richard',
    'cody',
    'john',
    'fred',
    'sarah',
    'sara',
    'django',
    'tupper',
    'noe',
    'aev',
    'cubed',
    'paradox',
    'hack',
    'spanner',
    // cube drone characters
    'cube',
    'drone',
    'walt',
    'sparky',
    'lain',
    'miloslav',
    'amanda',
    'xyzzy',
    'ceo',
    // groovelet characters
    'zariel',
    'oth',
    'cystam',
    'kiro',
    'audient',
    'mersenne',
    'world',
    'path',
    'curopal',
    'blit',
    'stacks',
    'misk',
    'groovelet',
    //rutherford
    'rutherford',
    'marcus',
    //adventures times
    'jake',
    'marcelline',
    'finn',
    //grumps
    'barry',
    'ross',
    'arin',
    'danny',
    'suzy',
    //days
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
    'flursday',
    'holiday',
    'blernsday',
    // worst baby names
    'abcde',
    'alphabeta',
    'airwrecka',
    'arson',
    'banana',
    'carrion',
    'chaos',
    'custard',
    'fellony',
    'gassy',
    'havoc',
    'henceforth',
    'taqueria',
    'uncle',
    'aunt',
    'window',
    'wind',
    'bort',
    'gorb',
    'barf',
    'barfinkel',
    'boomquisha',
    'shorbert',
    'clarm',
    'janarthanon',
    'crabitha',
    'tressica',
    'beff',
    'surfbort',
    'curbis',
    'curtalina',
    'curtina',
    'curtamundo',
    'subcurtaneous',
    'curtimurtimus',
    'jennennifer',
    'jonnannifer',
    'gennennifer',
    'kneel',
    'neeel',
    'neelix',
    'benjammin',
    'jenjamin',
    'robot',
    'tomtom',
    'carome',
    'pubert',
    'olga',
    'alicia',
    'fluffy',
    'boris',
    'ian',
    'tula',
    'melfrid',
    'mike',
    'felicity',
    'erwin',
    'bartholemew',
    'melvin',
    'mackenzie',
    'esmeralda',
    'gil',
    'sasha',
    'barney',
    'shaniqua',
    'sherlock',
    'watson',
    'boy',
    'baby',
    'uthgherd',
    'missing texture',
    'elizabreth',
    'belizabort',
    'beth',
    'bethany',
    'many bothans',
    'meldor',
    'olivia',
    'maverick',
    'beberly',
    'ermagerd',
    'danger',
    'merika',
    'yunique',
    'shakira',
    'beyonce',
    'vejonica',
    'derfla',
    'phelony',
    'moxie',
    'jessifer',
    'brick',
    'jammy',
    'mazen',
    'hunk',
    'prince',
    'cameron',
    'blanket',
    'jermajesty',
    'moon unit',
    'billy bob',
    'pillow',
    'pill',
    // just... names, I guess?
    'hope',
    'gertrude',
    'jack',
    'keith',
    'helga',
    'tiny',
    'kimmy',
    'willy',
    'elizabeth',
    'garden',
    'lawrence',
    'jessica',
    'king',
    'yoshi',
    'ichiro',
    'angus',
    'natasha',
    'alice',
    'lilly',
    'astrid',
    'saga',
    'freja',
    'wilma',
    'stella',
    'molly',
    'leah',
    'ines',
    'sigrid',
    'celine',
    'lykke',
    'joline',
    'marco',
    'lorenzo',
    'antonio',
    'vito',
    'eugene',
    'norberto',
    'diego',
    'luca',
    'giovanni',
    'stefano',
    'mario',
    'luigi',
    'laura',
    'rosa',
    'gianna',
    'pietro',
    'zhang wei',
    'liu wei',
    'li qiang',
    'chuck',
    'trent',
    'trenton',
    'chad',
    'chadwick',
    'harry',
    'steve',
    'storve',
    'yolanda',
    'tara',
    'rusty',
    'ivana',
    'owin',
    'owen',
    'testy',
    'tasty',
    'carl',
    'albert',
    'carlbert',
    'cornelius',
    'timothy',
    'tim',
    'kiko',
    'wilhelm',
    'pierre',
    'tiffany',
    'ben',
    'heather',
    'travis',
    'courteney',
    'tracy',
    'yang',
    'vivian',
    'ryan',
    'shirley',
    'shorley',
    'phil',
    'andy',
    'spalding',
    'joao',
    'gabriel',
    'lucas',
    'matheus',
    'victor',
    'luiz',
    'noah',
    'benjamin',
    'sophia',
    'emma',
    'liam',
    'garol',
    'jimothy',
    'tedward',
    'jacob',
    'logan',
    'chloe',
    'samuel',
    'jayden',
    'hannah',
    'avery',
    'zoe',
    'madison',
    'carter',
    'felix',
    'leo',
    'charles',
    'korg',
    'brincely',
    'quim',
    'aria',
    'grace',
    'hunter',
    'dylan',
    'audrey',
    'austin',
    'jaxon',
    'nora',
    'ivy',
    'romy',
    'levi',
    'juliet',
    'parker',
    'victor',
    'piper',
    'sara',
    'cole',
    'ryder',
    'simon',
    'lauren',
    'fyodor',
    'mark',
    'quigley',
    'endor',
    //norse gods
    'thor',
    'loki',
    'odin',
    'freya',
    'freyja',
    'frigg',
    'vanir',
    'njord',
    //outfielders
    'azazel',
    'haniel',
    'lailah',
    'metatron',
    'ramiel',
    'sachiel',
    'samael',
    'schemhampharae',
    'seraph',
    'lina',
    //celebritos
    'hanks',
    'damon',
    'brando',
    'smith',
    'frakes',
    'nimoy',
    'doohan',
    'chekov',
    'levar',
    'burton',
    'channing',
    'tatum',
    'tanning',
    'chatum',
    'depp',
    'clooney',
    'evans',
    'lawrence',
    'reynolds',
    'pitt',
    'rudd',
    'hardy',
    'pratt',
    'perry',
    'gadot',
    'godot',
    'elba',
    'cooper',
    'ridley',
    // most popular names
    'jose',
    'nushi',
    'maria',
    'wei',
    'yan',
    'abdul',
    'ying',
    'juan',
    'luis',
    'carlos',
    'elena',
    'xin',

    //simpsons
    'homer',
    'marge',
    'lisa',
    'bart',
    'ralph',
    'seymour',
    'chalmers',
    'nancy',
    'moe',
    'edna',
    'nelson',
    'milhouse',
    'ned',
    'waylon',
    'martin',
    'willie',
    //ranks
    'captain',
    'marshal',
    'lieutenant',
    'the',
    'the incredible',
    'the vast',
    'the endless',
    'the unforgettable',
    'the wonderful',
    'mister',
    'mr',
    'doctor',
    'missus',
    'grandma',
    'grandpa',
    'great aunt',
    'ms',
    'mrs',
    'lady',
    'dr',
    'lord',
    'ensign',
    'admiral',
    'officer',
    'wing commander',
    'vice admiral',
    'emperor',
    'super emperor',
    'rear admiral',
    'commodore',
    'colonel',
    'major general',
    'general',
    'corporal',
    'sargeant',
    'major',
    'private',
    'queen',
    'earl',
    'duke',
    'professor',
    // don't ask where these names came from
    'bonnie',
    'riley',
    'tasha',
    'mia',
    'kendra',
    'chanel',
    'adriana',
    'lily',
    'tori',
    'katja',
    'brandi',
    // these ones are just made up
    'chardonnay',
    'crystal',
    'brandy',
    'lola',
    'angel',
    'angeline',
    'anastasia',
    'cherry',
    'destiny',
    'raven',
    'scarlett',
    'scarlet',
    'layla',
    'tawny',
    'trinity',
    //futuramas
    'zaph',
    'zapp',
    'fry',
    'leela',
    'kif',
    'scruffy',
    'morbo',
    'nibbler',
    'farnsworth',
    // bojacks
    'bojack',
    'carolyn',
    //avatars
    'aang',
    'katara',
    'toph',
    'zuko',
    'sokka',
    'iroh',
    'appa',
    'azula',
    'suki',
    'jet',
    'tenzin',
    'bolin',
    'lin',
    'mako',
    //ricks
    'morty',
    'rick',
    //uncles
    'buck',
    'sam',
    'tom',
    'fatih',
    //dunes
    'chani',
    'paul',
    'atriedes',
    'kwisatz',
    'haderach',
    'harkonnen',
    // sandersons
    'adolin',
    'kholin',
    'sorin',
    // songs of ice and fire
    'daenarys',
    'khal',
    'sansa',
    'cersei',
    'gregor',
    'tyrion',
    'arya',
    'hodor',
    'petyr',
    'brienne',
    'robb',
    'daario',
    'bran',
    // stars war
    'luke',
    'leia',
    'chewie',
    'han',
    'solo',
    'ben',
    'darth',
    // homestars
    'homestar',
    'strongbad',
    'cheat',
    'coach',
    'bubs',
    'homsar',
    // homestucks
    'sassacre',
    'jegus',
    'egbert',
    'karkat',
    'gamzee',
    'vriska',
    'terezi',
    'equius',
    'rose',
    'sollux',
    'caliborn',
    'jade',
    'kanaya',
    'feferi',
    'aradia',
    'rufioh',
    'eridan',
    'roxy',
    'spades',
    'diamonds',
    'hearts',
    'clubs',
    'boxcars',
    'meenah',
    'scratch',
    'english',
    // treks
    'jean luc',
    'james',
    'scotty',
    'pavel',
    'spock',
    'spop',
    'worf',
    'picard',
    'crusher',
    'data',
    'geordi',
    'beverly',
    'wesley',
    // sitcoms
    'tobias',
    'funke',
    'gob',
    'bluth',
    'annyong',
    'tony',
    'oscar',
    'maeby',
    'swanson',
    'leslie',
    'meagle',
    'pam',
    'jim',
    'angela',
    'toby',
    'jan',
    'michael',
    'scott',
    'kevin',
    'dwight',
    'creed',
    'meredith',
    'nellie',
    'darryl',
    'roy',
    'karen',
    'stanley',
    //unpopular names
    'weston',
    'declan',
    'xander',
    'theodore',
    'rowan',
    'austin',
    'evan',
    'emerson',
    'quinn',
    'daria',
    'jocelyn',
    'willow',
    'allison',
    'delilah',
    'chastity',
    // pratchett
    'vimes',
    'prime',
    'weatherwax',
    // greeks
    'hades',
    'artemis',
    'zeus',
    'poseidon',
    'hermes',
    'hercules',
    'hera',
    'dionysus',
    'hades',
    'apollo',
    // months
    'january',
    'february',
    'march',
    'smarch',
    'april',
    'may',
    'june',
    'july',
    'august',
    'september',
    'october',
    'november',
    'december',
    // transformers
    'optimus',
    'megatron',
    'mega',
    'tron',
    'starscream',
    'bumblebee',
    'wheeljack',
    'jazz',
    //miyazakis
    'hayao',
    'catbus',
    'sophie',
    'howl',
    'sheeta',
    'fio',
    'chihiro',
    'sosuke',
    'haku',
    'arsene',
    'lupin',
    'caproni',
    // games
    'nobuo',
    'terra',
    'locke',
    'sabin',
    'gau',
    'cyan',
    'kefka',
    'shadow',
    'celes',
    'celeste',
    'umaro',
    'gogo',
    'mog',
    'kupo',
    'relm',
    'strago',
    'cloud',
    'strife',
    'tifa',
    'aeris',
    'seph',
    'barrett',
    'yuffie',
    'vivi',
    'steiner',
    'tidus',
    'yuna',
    'kimahri',
    'wakka',
    'lulu',
    'rikku',
    'lara',
    'croft',
    'legend',
    'zelda',
    'kirby',
    'falcon',
    'link',
    'samus',
    'kratos',
    'nathan',
    'snake',
    'gordon',
    'gord',
    'ezio',
    'ryu',
    'ken',
    'e honda',
    'blanka',
    'chun li',
    'nook',
    'isabelle',
    'leon',
    'niko',
    'morrigan',
    'aloy',
    'batman',
    'joker',
    'makoto',
    'ryuji',
    'futaba',
    'ann',
    'yusuke',
    'goro',
    'haru',
    'tae',
    'sadayo',
    'baron',
    'marie',
    'catherine',
    'clementine',
    'dutch',
    'edith',
    'sonya',
    'agent',
    'sonic',
    'sanic',
    'banjo',
    'mario',
    'wario',
    'luigi',
    'peach',
    'vocaloid',
    'sans',
    'papyrus',
    'toriel',
    'grillby',
    'skeleton',
    'dapper',
    'blook',
    'asriel',
    'ralsei',
    'spamton',
    'kromer',
    'jevil',
    'berdly',
    'hathy',
    'kris',
    'tasque',
    'noelle',
    'susie',
    'calvin',
    'hobbes',
    'lemming',
    'glados',
    'cave',
    'johnson',
    'wrex',
    'deckard',
    'fox',
    //muppets
    'kermit',
    'animal',
    'gonzo',
    'walter',
    'fozzie',
    'beaker',
    'honeydew',
    'benson',
    'rowlf',
    'piggy',
    // albums
    'honey',
    'bunny',
    'max',
    'aurora',
    'justice',
    'parov',
    'ladytron',
    'pat',
    'sylvan',
    'nena',
    'robyn',
    'icona',
    'regina',
    'grimes',
    'chromeo',
    'romeo',
    'french',
    'roxanne',
    'louie',
    'matthew',
    'galantis',
    'bruno',
    'kimbra',
    'ellie',
    //female scientists
    'rosalind',
    'ada',
    'lise',
    'dorothy',
    'hedy',
    'tu',
    'gerty',
    'jocelyn',
    'annie',
    //countries and places
    'britain',
    'london',
    'france',
    'paris',
    'nice',
    'germany',
    'munich',
    'italy',
    'rome',
    'milan',
    'naples',
    'turin',
    'palermo',
    'genoa',
    'bologna',
    'spain',
    'pamplona',
    'greece',
    'armenia',
    'holland',
    'amsterdam',
    'switzerland',
    'poland',
    'belgium',
    'waffle',
    'canada',
    'alberta',
    'nunavut',
    'squamish',
    'richmond',
    'langley',
    'burnaby',
    'westminster',
    'victoria',
    'vancouver',
    'bastad',
    'bath',
    'poco',
    'coquitlam',
    'kensington',
    'surrey',
    'hope',
    'kelowna',
    'osoyoos',
    'delta',
    'merritt',
    'penticton',
    'alberni',
    'duncan',
    'dawson',
    'creek',
    'grand',
    'forks',
    'revel',
    'stoke',
    'trail',
    'tofino',
    'saanich',
    'nanaimo',
    'quesnel',
    'moody',
    'toronto',
    'montreal',
    'whistler',
    'quebec',
    'newfie',
    'saskatchewan',
    'australia',
    'mexico',
    'tijuana',
    'puebla',
    'monterrey',
    'chihuahua',
    'belize',
    'sweden',
    'stockholm',
    'malmo',
    'norway',
    'bergen',
    'flekkefjord',
    'grimstad',
    'hammerfest',
    'horten',
    'molde',
    'oslo',
    'alta',
    'jersey',
    'hampshire',
    'puerto',
    'rico',
    'suave',
    'ceiba',
    'portugal',
    'lisbon',
    'amadora',
    'brazil',
    'paolo',
    'curitiba',
    'japan',
    'hokkaido',
    'tokyo',
    'nagoya',
    'toyohashi',
    'okazaki',
    'seto',
    'ichinomiya',
    'handa',
    'kasugai',
    'toyokawa',
    'tsushima',
    'hekinan',
    'anjo',
    'nishio',
    'gamagori',
    'nisshin',
    'yatomi',
    'miyoshi',
    'nagakute',
    'nisshin',
    'kariya',
    'korea',
    'seoul',
    'busan',
    'incheon',
    'daegu',
    'daejeon',
    'gwangju',
    'suwon',
    'uganda',
    'kampala',
    'antigua',
    'barbuda',
    'angola',
    'austria',
    'vienna',
    'linz',
    'graz',
    'belize',
    'bolivia',
    'bulgaria',
    'varna',
    'cuba',
    'czech',
    'djibouti',
    'obock',
    'estonia',
    'fiji',
    'guyana',
    'hungary',
    'jamaica',
    'jordan',
    'kenya',
    'laos',
    'latvia',
    'yemen',
    'tuvalu',
    'turkey',
    'tonga',
    'togo',
    'tonka',
    'singapore',
    'sierra',
    'leone',
    'sepia',
    'senegal',
    'marino',
    'samoa',
    'lucia',
    'vincent',
    'vince',
    //softwares
    'rands',
    'joel',
    //divinity
    'fane',
    'lohse',
    'sebille',
    //just whatever
    'fitzwilliam',
    'darcy',
    'tintin',
    // catch 22
    'yossarian',
    'cathcart',
    'major major',
    'orr',
    'metcalf',
    'popinjay',
    'snark',
    'stubbs',
    // groove
    'yzma',
    'kronk',
    'pacha',
    'eartha',
    'chaca',
    'tipo',
    // gideons
    'gideon',
    'harrow',
    'harrowhark',
    'tamsyn',
    'ortus',
    'lyctor',
    'palamedes',
    'camilla',
    'abigail',
    'magnus',
    'dulcinea',
    'ianthe',
    'judith',
    'silas',
    // umbrella
    'hazel',
    'chacha',
    'vanya',
    'luther',
    'klaus',
    'pogo',
    //pixars
    'gusteau',
    'remy',
    'barbie',
    'bailey',
    'bing bong',
    'brent',
    'bubbles',
    'cal',
    'chatter',
    'dante',
    'emile',
    'ernesto',
    'forky',
    'guido',
    'heimlich',
    'jacques',
    'luxo',
    'marlin',
    'mater',
    'miguel',
    'nash',
    'otis',
    'syndrome',
    'tuck',
    'roll',
    // ---- END OF NAMES
    'names',
    'arelli',
    'omoto',
    'slick',
    'slack',
    'ware',
    'puzzle',
    'bobble',
    'kart',
    'katamari',
    'shovel',
    'knight',
    // planets
    'mercury',
    'venus',
    'earth',
    'mars',
    'moon',
    'prism',
    'power',
    'jupiter',
    'uranus',
    'neptune',
    'pluto',
    // marketing buzzwords
    'brand',
    'brandalytics',
    'synergy',
    'analytics',
    'clickbait',
    'fraud',
    'disrupt',
    'viral',
    'freemium',
    'growth',
    'hacking',
    'hyper',
    'local',
    'innovate',
    'innovator',
    'ideate',
    'jacking',
    'key',
    'performance',
    'indicator',
    'initiative',
    'agile',
    'modern',
    'swift',
    'ion',
    'integration',
    'inter',
    'low hanging fruit',
    'millenial',
    'demographic',
    'demo',
    'graphic',
    'optimized',
    'omni',
    'channel',
    'placement',
    'engagement',
    'snackable',
    'craveable',
    'content',
    'upgrade',
    'transparent',
    'clear',
    'leader',
    'entrepreneur',
    'wearable',
    //colors
    'red',
    'blue',
    'yellow',
    'green',
    'indigo',
    'violet',
    'purple',
    'magenta',
    'maroon',
    'brown',
    'pink',
    'orange',
    'orchid',
    'turquoise',
    'royal',
    'salmon',
    'plaid',
    'almond',
    'beige',
    'azure',
    'striped',
    'coral',
    'fuchsia',
    'grellow',
    'lavender',
    'khaki',
    'cream',
    'navy',
    'slate',
    'silver',
    'copper',
    'bronze',
    'steel',
    'tomato',
    //animals
    'badger',
    'dolphin',
    'cat',
    'catto',
    'monkey',
    'ape',
    'birb',
    'snek',
    'doge',
    'dog',
    'bird',
    'deer',
    'cow',
    'dragon',
    'drake',
    'marmot',
    'vole',
    'shark',
    'minnow',
    //languages
    'python',
    'erlang',
    'java',
    'script',
    'ecma',
    'intercal',
    'malbolge',
    'lisp',
    'algol',
    'basic',
    'cobol',
    'fortran',
    'flash',
    'mumps',
    'caml',
    'delphi',
    'elixir',
    'emacs',
    'vim',
    'go',
    'haskell',
    'kotlin',
    'lynx',
    'logo',
    'modula',
    'ook',
    'ruby',
    'rust',
    'scala',
    'scheme',
    //monsters
    'goblin',
    'gremlin',
    'shade',
    'orc',
    'cyclops',
    'mirage',
    'bear',
    'demon',
    'daemon',
    'gorgon',
    'yeti',
    'beast',
    'golem',
    // nonsense
    'squidge',
    'futter',
    'fram',
    'mc',
    'og',
    'gog',
    'wonk',
    'clorb',
    'churb',
    'squimp',
    'imple',
    'clarp',
    'flam',
    'shorp',
    'squiff',
    'splarf',
    'erang',
    'bring',
    'copter',
    'ploinf',
    'ploink',
    'franp',
    'boom',
    'topia',
    'mazing',
    'tastic',
    'squim',
    'angle',
    'able',
    'ting',
    'booty',
    'pow',
    'mint',
    'chunk',
    'chonk',
    'chunky',
    'chonky',
    'whong',
    'focky',
    'dongl',
    'cronch',
    'kerk',
    'whingle',
    'swush',
    'thonp',
    'squish',
    'flap',
    //misspelled
    'spogooter',
    'shramp',
    'mofn',
    'banaba',
    'mork',
    'mogno',
    'boptats',
    'popapo',
    'blarborries',
    'kurger',
    'bing',
    //ideophone
    'well then',
    'welp',
    'crunch',
    'cranch',
    'boing',
    'swish',
    'thud',
    'twinkle',
    'doki',
    'bang',
    //onomatopoeia
    'moo',
    'quack',
    'woof',
    'meow',
    'oink',
    'chirp',
    'roar',
    'cluck',
    'baa',
    'splat',
    //adjectives
    'bad',
    'good',
    'worse',
    'worst',
    'wurst',
    'greedily',
    'greed',
    'great',
    'greatly',
    'small',
    'mini',
    'ugly',
    'derpy',
    'derp',
    'dorky',
    'dork',
    'fat',
    'childish',
    'fussy',
    'fuss',
    'soft',
    'softly',
    'chubby',
    'huge',
    'odd',
    'oddly',
    'sad',
    'sadly',
    'round',
    'rounded',
    'vast',
    'dirty',
    'ripe',
    'broad',
    'damp',
    'wet',
    'smelly',
    'smell',
    'funky',
    'funk',
    'fast',
    'speedy',
    'speed',
    'cavernous',
    'soupy',
    'soup',
    'soapy',
    'soap',
    'happy',
    'stuffy',
    'stuff',
    'shifty',
    'shift',
    'relation',
    'ship',
    'tangy',
    'tang',
    'thrifty',
    'thrift',
    'eggy',
    'egg',
    'soggy',
    'sog',
    // strange words
    'fungus',
    'aa',
    'queue',
    'vex',
    'flub',
    'kerfuffle',
    'phobia',
    'quine',
    'quire',
    'nope',
    // rude boys
    'bottom',
    'crap',
    'poo',
    'poop',
    'dump',
    'toilet',
    'poopfart',
    'shart',
    'stink',
    'stinky',
    'stanky',
    'butt',
    'fart',
    'fartfart',
    'farty',
    'dang',
    'darn',
    'snot',
    'cough',
    'bastard',
    //  foods
    'food',
    'smore',
    'cabbage',
    'bread',
    'ranch',
    'candy',
    'wheat',
    'bulgur',
    'quinoa',
    'cupcake',
    'muffin',
    'cookie',
    'loaf',
    'lard',
    'flank',
    'dough',
    'sugar',
    'flour',
    'baking',
    'soda',
    'licious',
    'squeeze',
    'lunchable',
    'warhead',
    'quaker',
    'oat',
    'puff',
    'jetpuffed',
    'dunkaroo',
    'orbit',
    'laffy',
    'taffy',
    'gusher',
    'meal',
    'oatmeal',
    'swirler',
    'dorito',
    'bubble',
    'bites',
    'marsh',
    'mallow',
    'powder',
    'cucumber',
    'pickle',
    'kale',
    'onion',
    'potato',
    'shallot',
    'ginger',
    'garlic',
    'sesame',
    'rice',
    'burger',
    'ham',
    'beef',
    'chicken',
    'pork',
    'lamb',
    'bison',
    'coffee',
    'tea',
    'cola',
    'chocolate',
    'vanilla',
    'strawberry',
    'straw',
    'raspberry',
    'rasp',
    'wrath',
    'berry',
    'velvet',
    'nyan',
    // tech
    'stack',
    'overflow',
    'hack',
    'cyber',
    'truck',
    'techno',
    'video',
    'audio',
    'micro',
    'armor',
    'astro',
    'mono',
    'meta',
    'morph',
    'nano',
    'chloro',
    'nega',
    'open',
    'navi',
    'co',
    'null',
    'plasma',
    'ram',
    'eva',
    'retro',
    'super',
    'sub',
    'hexa',
    'synchro',
    'synth',
    'thermo',
    'solid',
    'static',
    'section',
    'tank',
    'radio',
    'pack',
    'mass',
    'jig',
    'zig',
    'latch',
    'implant',
    'heavy',
    'fluid',
    'gel',
    'drill',
    'disk',
    'cube',
    'cone',
    'pyramid',
    'buoy',
    'baffle',
    'bank',
    'stream',
    'time',
    'tractor',
    'vial',
    'vertex',
    'point',
    'wave',
    'weave',
    'wand',
    'e-cybo',
    'pooch',
    'crypto',
    'chipset',
    'fan',
    'heat',
    'sink',
    'gpu',
    'drive',
    'crate',
    // misc
    'stain',
    'spot',
    'creep',
    'trap',
    'tarp',
    'shop',
    'load',
    'fudge',
    'chimp',
    'blister',
    'bill',
    'bone',
    'bugle',
    'twin',
    'triple',
    'tower',
    'card',
    'cannon',
    'celery',
    'chance',
    'chord',
    'child',
    'cloak',
    'copy',
    'frog',
    'dirt',
    'drop',
    'drug',
    'duck',
    'edge',
    'elbow',
    'error',
    'scam',
    'fibre',
    'finger',
    'flax',
    'flood',
    'foam',
    'fog',
    //songs
    'caravan',
    'palace',
    'garbage',
    'motel',
    'magic',
    'clash',
    'little',
    'lies',
    'contact',
    'tape',
    'muse',
    'daft',
    'punk',
    'wax',
    'tailor',
    'esso',
    'music',
    'classic',
    'rule',
    'world',
    'duran',
    'graffiti',
    'safe',
    'sound',
    'astronaut',
    'lucky',
    'tango',
    'fuego',
    'devil',
    'basket',
    'case',
    'dare',
    'stupid',
    'freak',
    'hill',
    'zone',
    'crazy',
    'panic',
    'disco',
    'psycho',
    'killer',
    'solar',
    'stone',
    'stocking',
    'garterbelt',
    'burning',
    'spider',
    'empty',
    'threat',
    'star',
    'scream',
    'knuckles',
    'fruit',
    'gallon',
    'game',
    'games',
    'goose',
    'geese',
    'ghost',
    'gold',
    'grease',
    'gym',
    'helmet',
    'hemp',
    'ice',
    'icon',
    'island',
    'jacket',
    'karate',
    'kick',
    'kidney',
    'latex',
    'lunch',
    'lettuce',
    'mallet',
    'march',
    'organ',
    'panther',
    'panties',
    'undies',
    'knickers',
    'boxers',
    'underoo',
    'emoji',
    'motion',
    'smarmy',
    'pear',
    'pig',
    'pizza',
    'bagel',
    'pop',
    'pound',
    'propane',
    'accessories',
    'rhythm',
    'rock',
    'roll',
    'saxophone',
    'ophone',
    'seagull',
    'spaghetti',
    'spaghett',
    'ravioli',
    'fusilli',
    'chef',
    'boyardee',
    'tuna',
    'bass',
    'haddock',
    'ancho',
    'chile',
    'chili',
    'umbrella',
    'wig',
    'zipper',
    'britches',
    'mystery',
    'skull',
    'bench',
    'secret',
    'mouse',
    'house',
    'thunder',
    'hunt',
    'fisher',
    'fish',
    'hook',
    'bean',
    'harvest',
    'mix',
    'mixer',
    'hand',
    'finger',
    'nose',
    'nostril',
    'canal',
    'ear',
    'eye',
    'heart',
    'mouth',
    'eyes',
    'shoulder',
    'belly',
    'face',
    'arm',
    'cheek',
    'fur',
    'claw',
    'shin',
    'snug',
    'tube',
    'jean',
    'plan',
    'disk',
    'horse',
    'horsehorse',
    'horsehorsehorse',
    'worm',
    'staple',
    'ball',
    'button',
    'byte',
    'canyon',
    'dance',
    'crayon',
    'sausage',
    'meat',
    'bacon',
    'wad',
    'napkin',
    'device',
    'cape',
    'chair',
    'person',
    'kitten',
    'puppy',
    'book',
    'clamp',
    'cloud',
    'code',
    'correct',
    'battery',
    'coast',
    'coin',
    'space',
    'key',
    'bucket',
    'stapler',
    'mug',
    'bottle',
    'cable',
    'note',
    'lamp',
    'shelf',
    'dong',
    'board',
    'job',
    'knife',
    'thing',
    'phone',
    'sweat',
    'pant',
    'boot',
    'sock',
    'socks',
    'hat',
    'ring',
    'wang',
    'wrap',
    'holder',
    'pen',
    'bag',
    'sword',
    'shield',
    'spear',
    'staff',
    'shaft',
    'length',
    'wide',
    'slab',
    'grub',
    'song',
    'axe',
    'lamp',
    'club',
    'cage',
    'hole',
    'ass',
    'chum',
    'chump',
    'jerk',
    'foot',
    'twitch',
    'spud',
    'cord',
    'light',
    'tree',
    'place',
    'bag',
    'grime',
    'sludge',
    'cloth',
    'jam',
    'jormp',
    //boardgames
    'meeple',
    'token',
    'chip',
    'turn',
    // verbs
    'jump',
    'aggrieve',
    'abscond',
    'twirl',
    'spin',
    'slap',
    'smack',
    'poke',
    'prod',
    'drop',
    'punch',
    'grab',
    'throw',
    'thrust',
    'slide',
    'dunk',
    'braise',
    'scatter',
    'slide',
    'dice',
    'hurl',
    'buy',
    'huck',
    'toast',
    'align',
    'sell',
    'move',
    'shoop',
    'trade',
    'steal',
    'flip',
    'blast',
    'clean',
    'clasp',
    'hasp',
    'hide',
    'swing',
    'swig',
    'pinch',
    'grasp',
    'palm',
    'examine',
    'taste',
    'ingest',
    'swallow',
    'snort',
    'juggle',
    'lift',
    'eat',
    'quaff',
    'quip',
    'quick',
    'chug',
    'spine',
    'crack',
    'fear',
    'assemble',
    'chug',
    'gulp',
    'thirst',
    'hunger',
    // random words
    'wall',
    'quiet',
    'bond',
    'prestige',
    'crude',
    'consolidate',
    'hive',
    'shiver',
    'shimmer',
    'manage',
    'wonder',
    'shape',
    'industry',
    'business',
    'blade',
    'diplomat',
    'behavior',
    'check',
    'runner',
    'model',
    'deport',
    'tune',
    'bank',
    'golf',
    'finance',
    'flush',
    'sacred',
    'traffic',
    'summit',
    'sulphur',
    'cottage',
    'cope',
    'rise',
    'sphere',
    'gem',
    'free',
    'late',
    'arch',
    'pull',
    'chord',
    'blank',
    'fax',
    'like',
    'weed',
    'gloom',
    'grudge',
    'ridge',
    'leash',
    'route',
    'stop',
    'deluxe',
    'supreme',
    'width',
    'height',
    'pure',
    'brouhaha',
    'brou',
    'greet',
    'wise',
    'haha',
    'malarkey',
    'ma',
    'larkey',
    'non',
    'sense',
    'wabbit',
    'mugwump',
    'mug',
    'wump',
    'cods',
    'wallop',
    'nin',
    'compoop',
    'donny',
    'brook',
    'petti',
    'shenanigan',
    'she',
    'nanigan',
    'snolly',
    'goster',
    'ulence',
    'gubbin',
    'doozy',
    'fard',
    'bumber',
    'shoot',
    'fuddy',
    'duddy',
    'gobbledy',
    'troglo',
    'vomit',
    'widder',
    'shins',
    'bloviate',
    'gym',
    'squat',
    'rack',
    'spindle',
    'trundle',
    'shake',
    'heft',
    'lob',
    'weight',
    'heavy',
    'mat',
    'matt',
    'tamarind',
    'efficient',
    'desert',
    'rain',
    'miss',
    'you',
    'everything',
    'girl',
    'boy',
    'angry',
    'dudgeon',
    'firkin',
    'folderol',
    'mayonnaise',
    'mayo',
    'butter',
    'catsup',
    'relish',
    'mustard',
    'ketchup',
    'beer',
    'wine',
    'vinegar',
    'malt',
    'socks',
    'shorts',
    'flummox',
    'noodle',
    'hoose',
    'ornery',
    'orrery',
    'ordinary',
    'regular',
    'boring',
    'bland',
    'mediocre',
    'forgettable',
    'fancy',
    'namby',
    'pamby',
    'goober',
    'yahoo',
    'horror',
    'comedy',
    'tragedy',
    'action',
    'bibble',
    'yule',
    'hole',
    'hum',
    'zinger',
    'zing',
    'hammer',
    'loquent',
    'mania',
    'frenzy',
    'madness',
    'snicker',
    'snack',
    'slash',
    'swoosh',
    'galumph',
    'frisson',
    'fudge',
    'quaff',
    'freude',
    'family',
    'feud',
    'jeopardy',
    'lethal',
    'bang',
    'shot',
    'down',
    'smart',
    'smort',
    'salt',
    'pepper',
    'sauce',
    'boye',
    'wing',
    'love',
    'what',
    'who',
    'where',
    'why',
    'when',
    'goop',
    'gump',
    'glamp',
    'squink',
    'mimi',
    'chart',
    'chaff',
    'wily',
    'wobbly',
    'wibbly',
    'timey',
    'wimey',
    'surprise',
    'find',
    'watch',
    'event',
    'travel',
    'health',
    'joke',
    'glass',
    'joy',
    'tumbler',
    'policy',
    'letter',
    'floor',
    'group',
    'term',
    'boat',
    'street',
    'slice',
    'lemon',
    'lime',
    'slime',
    'clap',
    'quig',
];

const names = fragments.slice(0, fragments.indexOf('names'));
const things = fragments.slice(fragments.indexOf('names'));

const tlds = [
    '.xyz',
    '.blue',
    '.org',
    '.com',
    '.net',
    '.link',
    '.click',
    '.wedding',
    '.sexy',
    '.red',
    '.black',
    '.pics'
];

const teams = [
    'squad',
    'tribe',
    'corps',
    'group',
    'department',
    'division',
    'team',
    'band',
    'gang',
    'club',
    'company',
    'party',
    'faction',
    'troupe',
    'trio',
    'outfit',
    'bunch',
    'community',
    'league',
    'mob',
    'pack',
    'horde',
    'clan',
    'association',
    'community',
    'cooperative',
    'corporation',
    'guild',
    'league',
    'union',
    'organization',
    'partnership',
    'society',
];

const alpha = 'abcdefghijklmnopqrstuvwxyz'.split("");

const alphanum = '0123456789abcdefghijklmnopqrstuvwxyz'.split("");

const choice = (array) => {
    /*
        choose a random element from a list
     */
    let uniqueArray = Array.from(new Set(array));
    if(uniqueArray.length === 0){
        return null;
    }
    let randomIndex = Math.floor(Math.random() * uniqueArray.length);
    return uniqueArray[randomIndex];
};

const squad = () => {
    return choice(teams);
};

const titleCase = (string_what_to_titlecasify) => {
    /*
        convert a string "like this" into a string "Like This"
    */
    var i, j, str, lowers, uppers;
    str = string_what_to_titlecasify.replace(/([^\W_]+[^\s-]*) */g, function(txt) {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });

    // Certain minor words should be left lowercase unless
    // they are the first or last words in the string
    lowers = ['A', 'An', 'The', 'And', 'But', 'Or', 'For', 'Nor', 'As', 'At',
        'By', 'For', 'From', 'In', 'Into', 'Near', 'Of', 'On', 'Onto', 'To', 'With'];
    for (i = 0, j = lowers.length; i < j; i++)
        str = str.replace(new RegExp('\\s' + lowers[i] + '\\s', 'g'),
            function(txt) {
                return txt.toLowerCase();
            });

    // Certain words such as initialisms or acronyms should be left uppercase
    uppers = ['Id', 'Tv'];
    for (i = 0, j = uppers.length; i < j; i++)
        str = str.replace(new RegExp('\\b' + uppers[i] + '\\b', 'g'),
            uppers[i].toUpperCase());

    return str;
};

const flipCoin = () => {
    /*
        flip a coin

        this coin is unfairly weighted, on account of it's a little heavier on its face
     */
    return Math.random() > 0.52
};

const fragment = () => {
    /*
        choose a random word fragment like "todd" or "butt"
     */
    return choice(fragments);
};

const firstname = () => {
    return choice(names);
};

const thing = () => {
    return choice(things);
};

const tld = () => {
    /*
        choose a random tld
     */
    return choice(tlds);
};

const slug = () => {
    /*
        create a random slug - like "fragment" but more likely to be safe to use in a URL or email address
     */
    return slugify(fragment())
};

const char = () => {
    return choice(alphanum);
};

const letter = () => {
    return choice(alpha);
};

const shortId = () => {
    //5 characters of randomness. Pretty good for small sets of objects, like server ids.
    return `${slug()}-${char()}${char()}${char()}`;
};

const mediumId = () => {
    //8 characters. Okay for things like request ids or mid-90's passwords.
    return `${slug()}${slug()}-${char()}${char()}${char()}${char()}`;
};

const longId = () => {
    // 10 characters. Okay for database IDs for things that you're not going to have millions of.
    //  past this you should probably just consider a uuid
    return `${slugify(username())}-${char()}${char()}${char()}-${char()}${char()}${char()}${char()}${char()}`;
};

const dumbhash = (val) => {
    let md = md5(val);

    let firstThree = parseInt(md.substring(0,3), 16) % fragments.length;
    let secondThree = parseInt(md.substring(3,6), 16) % fragments.length;

    return `${slugify(fragments[firstThree])}-${slugify(fragments[secondThree])}`;
};

const sentence = () => {
    /*
        create some words all in a row.
     */
    let sentenceLength = 5 + Math.floor(Math.random() * 5);

    return titleCase(fragment()) + " " + Array.from({length: sentenceLength}, (x, i) => fragment()).join(" ") + ".";
};

const lorem = () => {
    /*
        create some words all in a row.
     */
    return Array.from({length: 5}, (x, i) => sentence()).join(" ");
};

const hexarray = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'];

const hexchar = () => {
    return choice(hexarray);
};

const hexcolor = () => {
    /*
        returns a random six-hex string
        but no "#", you have to add that on your own
     */
    return `${hexchar()}${hexchar()}${hexchar()}${hexchar()}${hexchar()}${hexchar()}`;
};


const name = () => {
    /*
        create a full-ass name, like "Pete Hornburger" or "Todd Wangsack"
     */
    return titleCase(username())
};

const username = () => {
    /*
        create a username with a space in it, like "bort fortfart" or "crispy toolbags"
     */
    if(flipCoin()){
        return `${firstname()} ${thing()}${thing()}`;
    }
    else{
        return `${firstname()} ${letter()} ${thing()}${thing()}`;   
    }
};

const email = () => {
    /*
        create an email address
     */
    return `${mediumId()}@${slug().replace("'", "")}${tld()}`;
};

const imageUrl = (width, identifier) => {
    /*
        return a kind of random monster that's not very random at all really
     */
    if(width == null){
        width = 200;
    }
    if(identifier == null){
        identifier = `${slug()}${slug()}${slug()}`;
    }

    return `https://api.adorable.io/avatars/${width}/${identifier}.png`

};

const ip = () => {
    /*
        returns an IPV4 address like "192.12.154.1"
     */
    let first = Math.floor(Math.random() * 256);
    let second = Math.floor(Math.random() * 256);
    let third = Math.floor(Math.random() * 256);
    let fourth = Math.floor(Math.random() * 256);
    return `${first}.${second}.${third}.${fourth}`;
};

const mac = () => {
    /*
        returns an EUI-48 mac address like "00-02-aa-86-ef-0b"
     */
    let octets = [];
    for (let i = 1; i <= 6; i++) {
        let octet = Math.floor(Math.random() * 256).toString(16);
        octet = ('00' + octet).slice(-2);
        octets.push(octet);
    }
    octets.join("-");
};

const countries = ['CA', 'BY', 'BE', 'MA', 'NO', 'OM', 'SE', 'TV', 'US', 'ZQ', 'ZM', 'GB'];

const country = () => {
    /*
        returns a 2-letter country code like 'CA', or 'BY'
     */
    return choice(countries);
};

const birthdayLuxon = () => {
    /*
        returns a birthday as a Luxon date
     */
    let years_ago = 13 + Math.floor(Math.random() * 40);
    let months_ago = Math.floor(Math.random() * 12);
    let days_ago = Math.floor(Math.random() * 20);
    return DateTime.local().minus({years: years_ago, months: months_ago, days: days_ago})
};

const birthdayISO = () => {
    /*
        returns a birthday as an ISO date
     */
    return birthdayLuxon().toISO();
};

const birthday = () => {
    /*
        returns a birthday as a JS Date
     */
    return birthdayLuxon().toJSDate();
};

const groupName = () => {
    return choice([
        titleCase(`The ${thing()} ${thing()} ${squad()}`),
        titleCase(`The ${squad()} of ${thing()} ${thing()}s`),
        titleCase(`${thing()} ${thing()} ${squad()}`),
        titleCase(`${thing()}-${thing()} ${squad()}`),
    ])
};

const printSomeCrap = () => {
    for(let i = 0; i < 10; i++){
        console.log(name());
    }
    console.log("---------------------");
    console.log(firstname());
    console.log(thing());
    console.log(username());
    console.log(dumbhash(12500));
    console.log(dumbhash(username()));
    console.log(shortId());
    console.log(mediumId());
    console.log(longId());
    console.log(email());
    console.log(lorem());
    console.log(imageUrl());
    console.log(birthdayISO());
    console.log(country());
    console.log(ip());
    console.log(groupName());
};

//printSomeCrap();

module.exports = {
    choice,
    flipCoin,
    firstname,
    fragment,
    fragments,
    names,
    thing,
    things,
    slug,
    shortId,
    mediumId,
    longId,
    dumbhash,
    sentence,
    lorem,
    tld,
    hexchar,
    hexcolor,
    username,
    titleCase,
    name,
    email,
    imageUrl,
    ip,
    mac,
    country,
    birthdayLuxon,
    birthdayISO,
    birthday,
    groupName,
};
